"""Application services for orchestration, replay, and series control."""

from ai_agents_hw6.application.bonus import (
    BonusCredentials,
    BonusMatchResult,
    BonusMatchup,
    BonusPreflightError,
    bonus_agreement_sha256,
    build_bonus_agreement,
    build_bonus_match_evidence,
    build_bonus_schedule,
    preflight_bonus_endpoints,
    preflight_bonus_opponent,
    require_confirmed_bonus_agreement,
    run_external_bonus_series,
    validate_bonus_schedule,
    write_bonus_agreement,
    write_bonus_match_evidence,
)
from ai_agents_hw6.application.bonus_mock import (
    DeterministicBonusMock,
    build_bonus_mock_report,
    run_bonus_mock,
)
from ai_agents_hw6.application.evidence import build_evidence_manifest, write_evidence_manifest
from ai_agents_hw6.application.learning_eval import (
    evaluate_learning,
    write_learning_evaluation,
)
from ai_agents_hw6.application.mcp_client import (
    LocalMcpDecisionProvider,
    McpClientConfig,
    McpClientError,
    RoleMcpClient,
    preflight_clients,
    run_local_mcp_series,
)
from ai_agents_hw6.application.series import (
    SeriesObserver,
    SeriesResult,
    SeriesSettings,
    TechnicalFailure,
    first_legal_action_provider,
    run_series,
    write_engine_only_series,
    write_engine_only_series_with_policy,
)

__all__ = [
    "SeriesResult",
    "SeriesObserver",
    "SeriesSettings",
    "TechnicalFailure",
    "first_legal_action_provider",
    "run_series",
    "write_engine_only_series",
    "write_engine_only_series_with_policy",
    "LocalMcpDecisionProvider",
    "McpClientConfig",
    "McpClientError",
    "RoleMcpClient",
    "preflight_clients",
    "run_local_mcp_series",
    "build_evidence_manifest",
    "write_evidence_manifest",
    "BonusCredentials",
    "BonusMatchResult",
    "BonusMatchup",
    "BonusPreflightError",
    "bonus_agreement_sha256",
    "build_bonus_agreement",
    "build_bonus_match_evidence",
    "build_bonus_schedule",
    "preflight_bonus_endpoints",
    "preflight_bonus_opponent",
    "require_confirmed_bonus_agreement",
    "run_external_bonus_series",
    "validate_bonus_schedule",
    "write_bonus_agreement",
    "write_bonus_match_evidence",
    "DeterministicBonusMock",
    "build_bonus_mock_report",
    "run_bonus_mock",
    "evaluate_learning",
    "write_learning_evaluation",
]
